default[:cakephp][:app_dir] = "/mnt/srv/www/strainsource/current/src/app"
default[:cakephp][:tmp_dir] = default[:cakephp][:app_dir] + "/tmp"
default[:cakephp][:upload_tmp_dir] = default[:cakephp][:app_dir]  + "/webroot/resources/tmp"
default[:cakephp][:upload_dir] = default[:cakephp][:app_dir]  + "/webroot/tmp"
default[:cakephp][:resources_dir] = default[:cakephp][:app_dir]  + "/resources"
default[:cakephp][:db_user] = "strainsource"
default[:cakephp][:db_name] = "strainsource"
default[:cakephp][:log_level] = "strainsource"
default[:cakephp][:debug_level] = 0